# Generated by Django 2.1.1 on 2019-06-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=40)),
                ('content', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Hash'),
        ),
    ]
